homepage:
    path: /
    controller: App\Controller\HomeController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

dashboard-employe:
    path: /tableau-de-bord-employe
    controller: App\Controller\DashboardEmployeeController::index

dashboard-admin:
    path: /tableau-de-bord-admin
    controller: App\Controller\DashboardAdminController::index

used-car:
    path: /voitures-occasion
    controller: App\Controller\UsedCarController::index

used-car-description:
    path: /voitures-occasion/details
    controller: App\Controller\UsedCarDescriptionController::index