homepage:
    path: /
    controller: App\Controller\HomeController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

dashboard-employe-1:
    path: /tableau-de-bord-employe
    controller: App\Controller\DashboardEmployeeController::index

dashboard-employe-2:
    path: /tableau-de-bord-employe/nouvelle-voiture
    controller: App\Controller\DashboardEmployeeNewCarController::index

dashboard-employe-3:
    path: /tableau-de-bord-employe/moderer-les-avis
    controller: App\Controller\DashboardEmployeeReviewsController::index

dashboard-employe-4:
    path: /tableau-de-bord-employe/ajouter-un-avis
    controller: App\Controller\DashboardEmployeeNewReviewController::index

dashboard-admin-1:
    path: /tableau-de-bord-admin
    controller: App\Controller\DashboardAdminController::index

dashboard-admin-2:
    path: /tableau-de-bord-admin/nouvel-employe
    controller: App\Controller\DashboardAdminNewEmployeeController::index

dashboard-admin-3:
    path: /tableau-de-bord-admin/moderer-les-services
    controller: App\Controller\DashboardAdminModerateServiceController::index

dashboard-admin-4:
    path: /tableau-de-bord-admin/nouveau-service
    controller: App\Controller\DashboardAdminNewServiceController::index

used-car:
    path: /voitures-occasion
    controller: App\Controller\UsedCarController::index

used-car-description:
    path: /voitures-occasion/details
    controller: App\Controller\UsedCarDescriptionController::index