homepage:
    path: /
    controller: App\Controller\HomeController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::index

connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::index

dashboard-employe:
  path: /tableau-de-bord-employe::index

dashboard-admin:
  path: /tableau-de-bord-admin::index

used-car:
  path: /voitures-occasion::index

used-car-description:
  path: /voitures-occasion/details::index